# -*- coding: utf-8 -*-
"""ComputeSales.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/github/andreac941/Pruebas_Software_Aseguramiento_Calidad_A01034993/blob/main/ComputeSales.ipynb
"""

import json
import sys
import time

def main():
    if len(sys.argv) != 3:
        print("Usage: python computeSales.py priceCatalogue.json salesRecord.json")
        sys.exit(1)

    price_catalogue_path = sys.argv[1]
    sales_record_path = sys.argv[2]

    try:
        with open(price_catalogue_path, 'r') as price_catalogue_file:
            price_catalogue_list = json.load(price_catalogue_file)
    except Exception as e:
        print(f"Error reading price catalog file: {e}")
        sys.exit(1)

    try:
        with open(sales_record_path, 'r') as sales_record_file:
            sales_record = json.load(sales_record_file)
    except Exception as e:
        print(f"Error reading sales record file: {e}")
        sys.exit(1)

    price_catalogue = {product["title"]: product for product in price_catalogue_list}

    start_time = time.time()

    total_cost = 0
    for sale in sales_record:
        try:
            product_title = sale['Product']
            quantity = sale['Quantity']
            price = price_catalogue[product_title]['price']
            total_cost += price * quantity
        except KeyError as e:
            print(f"Error processing sale: {e}")

    elapsed_time = time.time() - start_time

    print(f"Total cost: {total_cost}\nElapsed time: {elapsed_time} seconds")

    with open("SalesResults.txt", "w") as results_file:
        results_file.write(f"Total cost: {total_cost}\nElapsed time: {elapsed_time} seconds")

if __name__ == "__main__":
    main()