# -*- coding: utf-8 -*-
"""wordCount.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PDXaSIIStra1NEn1SBJ3KMvaNYyygsi_
"""

import sys
import time

def count_words(file_path):
    """
    Count the frequency of distinct words in the specified file.

    Parameters:
    - file_path (str): The path to the input file.

    Returns:
    - dict: A dictionary containing distinct words as keys and their frequencies as values.
    """
    try:
        with open(file_path, 'r', encoding='utf-8') as file:
            words = file.read().split()
    except FileNotFoundError:
        print(f"Error: File '{file_path}' not found.")
        return None
    except Exception as e:
        print(f"Error reading file: {e}")
        return None

    word_count = {}
    for word in words:
        # Remove non-alphanumeric characters from the word
        cleaned_word = ''.join(char.lower() for char in word if char.isalnum())
        if cleaned_word:
            word_count[cleaned_word] = word_count.get(cleaned_word, 0) + 1

    return word_count

def print_and_save_results(word_count, elapsed_time):
    """
    Print and save the word count results along with the elapsed time.

    Parameters:
    - word_count (dict): A dictionary containing distinct words and their frequencies.
    - elapsed_time (float): The time taken for the execution of the program.

    Returns:
    - None
    """
    # Print results on the console
    print("Word Count Results:")
    for word, count in word_count.items():
        print(f"{word}: {count}")

    # Save results to WordCountResults.txt
    with open("WordCountResults.txt", 'w', encoding='utf-8') as results_file:
        results_file.write("Word Count Results:\n")
        for word, count in word_count.items():
            results_file.write(f"{word}: {count}\n")

    # Print elapsed time
    print(f"\nTime Elapsed: {elapsed_time:.5f} seconds")
    # Save elapsed time to WordCountResults.txt
    with open("WordCountResults.txt", 'a', encoding='utf-8') as results_file:
        results_file.write(f"\nTime Elapsed: {elapsed_time:.5f} seconds")

def main():
    """
    This function allows to run the wordCount.py program to run.
    To record the start_time, to calculate the elapsed_time.
    And finally run the function print_and_save_results.
    """
    if len(sys.argv) != 2:
        print("Usage: python wordCount.py fileWithData.txt")
        sys.exit(1)

    file_path = sys.argv[1]

    start_time = time.time()

    word_count = count_words(file_path)

    end_time = time.time()
    elapsed_time = end_time - start_time

    if word_count is not None:
        print_and_save_results(word_count, elapsed_time)

if __name__ == "__main__":
    main()
