# -*- coding: utf-8 -*-
"""test_customer.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1E9KQyl4A8RRdvuhk78nnkSfnMB41eZWL
"""

import unittest
from hotel_management import Hotel, Reservation, Customer


class TestCustomerMethods(unittest.TestCase):
    def setUp(self):
        self.customer = Customer("John Doe", "john@example.com", "123456789")

    def test_create_customer(self):
        self.assertEqual(self.customer.name, "John Doe")
        self.assertEqual(self.customer.email, "john@example.com")
        self.assertEqual(self.customer.phone, "123456789")

    def test_delete_customer(self):
        initial_count = len(Customer.all_customers)
        self.customer.delete_customer()
        self.assertNotIn(self.customer, Customer.all_customers)
        self.assertEqual(len(Customer.all_customers), initial_count - 1)

    def test_display_information(self):
        expected_information = "Name: John Doe, Email: john@example.com, Phone: 123456789"
        self.assertEqual(self.customer.display_information(), expected_information)

    def test_modify_information(self):
        self.customer.modify_information(name="Jane Doe", email="jane@example.com", phone="987654321")
        self.assertEqual(self.customer.name, "Jane Doe")
        self.assertEqual(self.customer.email, "jane@example.com")
        self.assertEqual(self.customer.phone, "987654321")


if __name__ == '__main__':
    unittest.main()