# -*- coding: utf-8 -*-
"""test_reservation.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1E9KQyl4A8RRdvuhk78nnkSfnMB41eZWL
"""

import unittest
from hotel_management import Hotel, Reservation, Customer


class TestReservationMethods(unittest.TestCase):
    def setUp(self):
        customer = Customer("John Doe", "john@example.com", "123456789")
        hotel = Hotel("Test Hotel", "Test Location", 10)
        self.reservation = Reservation(customer, hotel, room_number=1, start_date="2024-02-20", end_date="2024-02-25")

    def test_create_reservation(self):
        self.assertEqual(self.reservation.customer.name, "John Doe")
        self.assertEqual(self.reservation.hotel.name, "Test Hotel")
        self.assertEqual(self.reservation.room_number, 1)
        self.assertEqual(self.reservation.start_date, "2024-02-20")
        self.assertEqual(self.reservation.end_date, "2024-02-25")

    def test_cancel_reservation(self):
        success, message = self.reservation.cancel_reservation()
        self.assertTrue(success)
        self.assertTrue(self.reservation.is_canceled())
        self.assertEqual(message, "Reservation successfully canceled")

    def test_is_canceled(self):
        self.assertFalse(self.reservation.is_canceled())
        self.reservation.cancel_reservation()
        self.assertTrue(self.reservation.is_canceled())


if __name__ == '__main__':
    unittest.main()