# -*- coding: utf-8 -*-
"""test_hotel.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1E9KQyl4A8RRdvuhk78nnkSfnMB41eZWL
"""

import unittest
from hotel_management import Hotel, Reservation, Customer


class TestHotelMethods(unittest.TestCase):
    def setUp(self):
        self.hotel = Hotel("Test Hotel", "Test Location", 10)

    def test_create_reservation(self):
        customer = Customer("John Doe", "john@example.com", "123456789")
        room_number = 1
        start_date = "2024-02-20"
        end_date = "2024-02-25"
        reservation = self.hotel.create_reservation(customer, room_number, start_date, end_date)
        self.assertIn(reservation, self.hotel.reservations)

    def test_cancel_reservation(self):
        customer = Customer("John Doe", "john@example.com", "123456789")
        room_number = 1
        start_date = "2024-02-20"
        end_date = "2024-02-25"
        reservation = self.hotel.create_reservation(customer, room_number, start_date, end_date)
        self.assertTrue(self.hotel.cancel_reservation(reservation))
        self.assertNotIn(reservation, self.hotel.reservations)

    def test_display_information(self):
        expected_information = "Hotel: Test Hotel, Location: Test Location, Rooms: 10"
        self.assertEqual(self.hotel.display_information(), expected_information)

    def test_modify_information(self):
        self.hotel.modify_information(name="New Test Hotel", location="New Test Location", rooms=20)
        self.assertEqual(self.hotel.name, "New Test Hotel")
        self.assertEqual(self.hotel.location, "New Test Location")
        self.assertEqual(self.hotel.rooms, 20)

    def test_reserve_room(self):
        customer = Customer("John Doe", "john@example.com", "123456789")
        room_number = 1
        start_date = "2024-02-20"
        end_date = "2024-02-25"
        success, reservation = self.hotel.reserve_room(customer, room_number, start_date, end_date)
        self.assertTrue(success)
        self.assertIn(reservation, self.hotel.reservations)

    def test_cancel_room_reservation(self):
        customer = Customer("John Doe", "john@example.com", "123456789")
        room_number = 1
        start_date = "2024-02-20"
        end_date = "2024-02-25"
        reservation = self.hotel.create_reservation(customer, room_number, start_date, end_date)
        self.assertTrue(self.hotel.cancel_room_reservation(reservation))
        self.assertNotIn(reservation, self.hotel.reservations)


if __name__ == '__main__':
    unittest.main()